// Copyright Epic Games, Inc. All Rights Reserved.
FAreaLight CreateAreaLight(float Roughness, half3 N, half3 V, FCapsuleLight Capsule, bool bInverseSquared )
{
	FAreaLight AreaLight = InitAreaLight();

	// Clip to horizon
	//float NoP0 = dot( N, Capsule.LightPos[0] );
	//float NoP1 = dot( N, Capsule.LightPos[1] );
	//if( NoP0 < 0 ) Capsule.LightPos[0] = (  Capsule.LightPos[0] * NoP1 - Capsule.LightPos[1] * NoP0 ) / ( NoP1 - NoP0);
	//if( NoP1 < 0 ) Capsule.LightPos[1] = ( -Capsule.LightPos[0] * NoP1 + Capsule.LightPos[1] * NoP0 ) / (-NoP1 + NoP0);

	BRANCH
	if( Capsule.Length > 0 )
	{
		LineIrradiance( Capsule.LightPos[0], Capsule.LightPos[1], Capsule.DistBiasSqr, AreaLight.LineCosSubtended, AreaLight.Falloff, AreaLight.DiffuseL );
		AreaLight.NoL = dot( N, AreaLight.DiffuseL );
		AreaLight.DiffuseL = normalize( AreaLight.DiffuseL );
	}
	else
	{
		float DistSqr = dot( Capsule.LightPos[0], Capsule.LightPos[0] );
		AreaLight.Falloff = rcp( DistSqr + Capsule.DistBiasSqr );

		AreaLight.DiffuseL = Capsule.LightPos[0] * rsqrt( DistSqr );
		AreaLight.NoL = dot( N, AreaLight.DiffuseL );
	}

	if( Capsule.Radius > 0 )
	{
		// TODO Use capsule area?
		float SinAlphaSqr = saturate( Pow2( Capsule.Radius ) * AreaLight.Falloff );
		AreaLight.NoL = SphereHorizonCosWrap( AreaLight.NoL, SinAlphaSqr );
	}

	AreaLight.NoL = saturate( AreaLight.NoL );
	AreaLight.Falloff = bInverseSquared ? AreaLight.Falloff : 1;

	float3 ToLight = Capsule.LightPos[0];
	if( Capsule.Length > 0 )
	{
		float3 R = reflect( -V, N );

		#if 0
			// Fix hard edge when ray is nearly parallel to line
			float3 PointOnLine = ClosestPointLineToPoint( Capsule.LightPos[0], Capsule.LightPos[1], Capsule.Length );
			float3 DirToLine = normalize( PointOnLine );
			R = lerp( DirToLine, R, saturate( dot( DirToLine, R ) ) );
			R = normalize( R );
		#endif

		ToLight = ClosestPointLineToRay( Capsule.LightPos[0], Capsule.LightPos[1], Capsule.Length, R );
	}

	float DistSqr = dot( ToLight, ToLight );
	float InvDist = rsqrt( DistSqr );
	AreaLight.SpecularL = ToLight * InvDist;
	
	float a = Pow2( Roughness );
    
	// Diffuse micro reflection contribution will softly fade out when th light become an area light.
	// We only based this assumption based on the light size.
	const float SizeFadesOutDiffuseMicroRefl = 20.0;

	AreaLight.SphereSinAlpha = saturate( Capsule.Radius * InvDist * (1 - a) );
	AreaLight.SphereSinAlphaSoft = saturate( Capsule.SoftRadius * InvDist );

	SetIsRectLight(AreaLight, false);
	SetAreaLightDiffuseMicroReflWeight(AreaLight, saturate(1.0f - max(Capsule.Length, Capsule.Radius) / SizeFadesOutDiffuseMicroRefl));

	return AreaLight;
}

